### ISSUE TITLE
About the results on Office-31

### ISSUE THREAD

**Issue by davidpqc1231** [FengHZ/KD3A#1]
Thank you so much for your amazing work! But I have seen that you add the Office-31 option in this implementation, while the related results are not presented in the paper? Could you please give the test accuracies on this dataset?

**Comment by FengHZ** [comment]
Well, some reviewers said office31 is not a suitable benchmark since different works have different settings, so we remove the results on it. You may leave me a mail and I will send you the related results.

**Comment by davidpqc1231** [comment]
Thank you so much for your response @FengHZ ! My email is qupeng@iu.edu
