### ISSUE TITLE
The result of the experiment？

### ISSUE THREAD

**Issue by kongfany** [FengHZ/KD3A#4]
论文表格中实验的结果是针对每个域作为目标域进行单独训练得到的，还是只是针对目标域为Clipart？

**Comment by kongfany** [comment]
如果是针对目标域为clipart的话，那么数据集Digit5的表格中的数据是针对哪个目标域进行的？

**Comment by FengHZ** [comment]
We use one domain as target and use the rest as source domains. Digit-5 has 5 domains as mm mnist svhn ups and syn, and Clipart is for DomainNet.

**Comment by kongfany** [comment]
感谢您的回复。可能是我的提问存在问题，我没有很清晰的理解到您的意思。
我理解的是论文中 table 1 的数据是以 clipart 为目标域得到的clipart的数据，其他域的数据是本次训练中作为源域（目标域是 clipart ）测试所得到的结果（ 1 次训练）。但在论文看到需要针对每个目标域训练得到结果，table 1 中其他域的数据是分别作为目标域得到的结果吗（ 6 次训练）？
请问 table 1 中的其他域的数据是那种方式测试所得？
按照您的意思是 DomainNet 数据集以 clipart 为目标域（一次训练）得到了 table1 中的所有数据？那 Digit-5 数据集对应的 table 6 呢？

**Comment by kongfany** [comment]
Thank you for your reply. Maybe there is something wrong with my expression. I didn't understand your meaning clearly.
For the results in table 1 of the paper are the data obtained from a training (target domain is Clipart), are the data in other domains the data in the source domain of this training(only once)? Or is it just the clipart column in Table 1 that is the result of this experiment, and the other columns need to be trained separately as the target domain to get the result(Each training target domain is one of Clipart Infograph Painting Quickdraw Real Sketch,for a total of 6 times.)?
In addition, the results in table 6 are obtained from the training of which target domain? (which one from mm mnist svhn ups and syn)
Looking forward to your reply.

**Comment by kongfany** [comment]
> We use one domain as target and use the rest as source domains. Digit-5 has 5 domains as mm mnist svhn ups and syn, and Clipart is for DomainNet.

Thank you for your reply. Maybe there is something wrong with my expression. I didn't understand your meaning clearly.
For the results in table 1 of the paper are the data obtained from a training (target domain is Clipart), are the data in other domains the data in the source domain of this training(only once)? Or is it just the clipart column in Table 1 that is the result of this experiment, and the other columns need to be trained separately as the target domain to get the result(Each training target domain is one of Clipart Infograph Painting Quickdraw Real Sketch,for a total of 6 times.)?
In addition, the results in table 6 are obtained from the training of which target domain? (which one from mm mnist svhn ups and syn)
Looking forward to your reply.

**Comment by FengHZ** [comment]
Yes. For DomainNet, we perform 6 experiments, each with one domain as target and others as source domains (for example, exp 1: Clipart as target and Infograph, Painting, Quickdraw, Real, Sketch as source domains, exp 2: Infograph as target and others as source domains ...). For Digit-5, we perform 5 experiments with the same settings.
